server:  
  port: ${PORT:8888}
    
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/garyrosebk/gittest.git
          username: ${github.username}
          password: ${github.password}
          cloneOnStart: true
  profiles:
    active: native
          
github:
  username: garyrosebk@gmail.com
  password: rmfodkfdkTek45^^