server:
  port: ${PORT:8090}
  
logging:
  file: logs/order.log
  level:
#    com.netflix: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
#    console: "%d{HH:mm:ss.SSS} %-5level %msg%n"
    file: "%d{HH:mm:ss.SSS} %-5level %msg%n"  
  
account-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8091
customer-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8092
product-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8093
  
#spring:
#  application:
#    name: order-service
# profiles: 
#    active: zone1  
#eureka:
#  instance:
#    instance-id: ${spring.application.name}-${server.port}
#   prefer-ip-address: true  
#    metadataMap:
#     zone: zone1
# client:
#    serviceUrl:
#     defaultZone: http://localhost:8761/eureka/
#      preferSameZoneEureka: true
     