server:
  port: 8090
account-service:
  riboon:
    eureka:
      enabled: false
    listOfServers: localhost:8091
customer-service:
  riboon:
    eureka:
      enabled: false
    listOfServers: localhost:8092
product-service:
  riboon:
    eureka:
      enabled: false
    listOfServers: localhost:8093    
      
spring:
  appication:
    name: order-service