eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
    registryFetchIntervalSeconds: 10
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 3
    disable-delta: true