eureka:
  instance:
    hostname: localhost
    metadataMap:
      zone: zone3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registerWithEureka: false
    fetchRegistry: false

server:  
  port: 8763