server:  
  port: 8888

spring:
  application:
    name: config-server
  cloud:    config:      server:
        git: 
          uri: https://github.com/garyrosebk/config-repo.git
          clone-on-start: true
          username: ${github.username}
          password: ${github.password}
#         vault:
#           host: 192.168.99.100
#           port: 8200
eureka:
  instance:
    metadataMap:
      zone: zone1
    lease-renewal-interval-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/     
    registryFetchIntervalSeconds: 10
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 3
    disable-delta: true

github:
  username: garyrosebk@gmail.com
  password: rmfodkfdkTek45^^