server:
  port: ${PORT:8761}
  
spring:
  application:
    name: discovery-service
  profiles:
    active: zone1
  
eureka:  client:    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-expiration-duration-in-seconds: 90
    hostname: localhost
    metadataMap:
      zone: zone1
    
#logging:
#  path: /tmp/discovery/logs