server:
  port: ${PORT:8092}
  
spring:
  application:
    name: customer-service
  profiles: zone1
eureka:
  instance:
    metadata-map:      zone: zone1
  client:
    service-url:      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG 
 