server:
  port: ${PORT:8093}
  
spring:
  application:
    name: product-service
  profiles: 
    active: zone1
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
    metadataMap:
      zone: zone1
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
      
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
