spring:
  application:
    name: account-service
  profiles: 
    active: zone1
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true    
    metadata-map:
      zone: zone1
  client:
    serviceUrl:      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
server:
  port: ${PORT:8091}